### PR TITLE
#81 Implement About page

### LINKED ISSUE #81: [About Page] Implement page features and its reusable components
Welcome onboard....
Here's an opportunity to contribute to the "About Page" of the [Badging Website.](https://badging-website.netlify.app/)

The "About Page" is an integral part of this website and we want your work on this to align with the beautiful [prototype](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=488%3A886&t=yaPK6oov4kd7YU9u-0) we designed. Kindly ensure that your design is mobile friendly and neatly responsive to different screen sizes.

**Reusable Components** 
The following sections of the About Page must be designed independently, and imported into their respective sections:
- Motivation To Apply Section
- Submit Your Event for DEI Badge Section

You are required to inspect the UI design [here](https://www.figma.com/file/7tiuJbwakgDu15mOjzKTDK/Badging-Website?node-id=2115%3A6635&t=yaPK6oov4kd7YU9u-0) and provide an updated version your work by cloning the main branch.

Your final work must look like this

About Us

If you want this task to be assigned to you, kindly inform us via the comment section.
Thank you for your contribution!

### PR DESCRIPTION
**Pull request by Holajuwon**
#### What does this PR do?
Implements the about page

#### Description of Task to be completed?
- add styles to already created components
- added responsiveness

#### How should this be manually tested?
- go to `/about` to see new changes

Finishes #81

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by Maryblessing** [comment]
Hi @Holajuwon, thank you so much for working on this issue

**Comment by Maryblessing** [comment]
Hello @Teek-tech @kaxada, can you please help review this pull request so we close it up? 

Thank you

**Comment by kaxada** [comment]
thanks @Maryblessing. I am on it

**Comment by Maryblessing** [comment]
Hi @kaxada, how did this go? Is it good to go? Can we close it up now?

**Pull request merged**
