### PR TITLE
#84-Implement 404 page

### LINKED ISSUE #84: Implement 404 page

### PR DESCRIPTION
**Pull request by meenarh**
Designed the error 404 page.

### CODE REVIEW

**Comment by Teek-tech** [comment]
Hello @meenarh, 
Thanks for your contributions, we appreciate your effort.

You seem to have some issues we need to fix.
Kindly follow these steps to replicate and fix the problem.
- Pull from the main branch
- run `npm install`
- Create a new branch
- Run the project to ensure everything works fine.
- Merge your the existing branch you worked on with the new branch
- Run you code and inspect to see if there is any error. You should be able to resolve them if you find any. If you can't, kindly drop a message here to enable us assist you.
- Create a new pull request

Thanks.

**Comment by kaxada** [comment]
@meenarh please look at these reviews above this Thread

**Comment by Maryblessing** [comment]
Hello @meenarh, following up on this issue. Have you taken a look at the comments above? Is there any challenge you're facing and need help on? Please let us know so we can wrap this up. 

Looking forward to hearing from you

**Comment by meenarh** [comment]
Hi @Maryblessing I didn't receive notifications about them. I'll resolve the issues and make another PR. Thank you for reaching out

**Comment by meenarh** [comment]
Will the new branch I'm creating have a new issue number? As this one is 84, can I use say 85 now?

**Comment by kaxada** [comment]
@meenarh just create a new branch and reimplement your solution. I'll close this one for now. Thank you @Maryblessing for looking out.

**Comment by meenarh** [comment]
Okay. thank you

**Pull request closed without merging**
